<?php
get_header();
get_template_part('partials/home/banner');
get_template_part('partials/home/intro');
get_template_part('partials/home/mostras');
//get_template_part('partials/home/thematic');
//get_template_part('partials/home/tribute');
//get_template_part('partials/home/bcm');
//get_template_part('partials/home/debate');
get_template_part('partials/home/masterclass');
//get_template_part('partials/home/art');
//get_template_part('partials/home/sections');
get_template_part('partials/home/gallery');
get_template_part('partials/home/tv');
get_template_part('partials/home/news');
//get_template_part('partials/home/timeline');
get_template_part('partials/home/brands');
get_footer();
